export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const GET_POST = 'GET_POST'
export const RESET_POST = 'RESET_POST'
export const TOGGLE_POST_LOADING = 'POST_LOADING'

export const GET_POSTS = 'GET_POSTS'
export const TOGGLE_POSTS_LOADING = 'POSTS_LOADING'

export const TOGGLE_COMMENT_UPDATING = 'TOGGLE_COMMENT_UPDATING'
